version: "3.9"
services:
 db:
   image: mysql
   container_name: mysql
   environment:
     MYSQL_ALLOW_EMPTY_PASSWORD: yes
   ports:
   - "3306:3306"
   volumes:
     - jeff_data:/var/lib/mysql

volumes:
  jeff_data:



